site_name: Python Course 2022
theme:
  favicon: 'img/favicon.ico'
  name: material
markdown_extensions:
  - admonition

site_url: https://ueapy.github.io/pythoncourse2022-website
repo_url: https://github.com/ueapy/pythoncourse2022-website
site_author: Eliza Karlowska (after Tiago Silva and after Denis Sergeev)
docs_dir: src
site_dir: _site

nav:
  - Home: index.md
  - Programme: programme.md
  - Content: content.md
  - Installation: installation.md
  - Resources: resources.md
